// @generated by scripts/generate-branding.ps1 — DO NOT EDIT BY HAND
#![allow(dead_code)]

pub const DISPLAY_SILENT_NAME: &str = "Chimera++";
pub const DISPLAY_MANAGER_NAME: &str = "Chimera++ 管理工具";
pub const PUBLISHER: &str = "ChimeraHub";
pub const REPOSITORY: &str = "Duojiyi/chimera-codex";
pub const LATEST_JSON_URL: &str =
    "https://github.com/Duojiyi/chimera-codex/releases/latest/download/latest.json";
pub const DEFAULT_RELAY_BASE_URL: &str = "https://api.chimerahub.org/v1";
pub const DEFAULT_RELAY_MODEL: &str = "gpt-5.5";
pub const ARTIFACT_PREFIX: &str = "ChimeraPlusPlus";
pub const MACOS_BUILD_NUMBER: u32 = 3;
pub const WEBSITE_URL: &str = "https://api.chimerahub.org/";
pub const API_KEY_URL: &str = "https://api.chimerahub.org/";
