//! Capability manifest — skin compatibility, bound to stable raw digest (Spec 9.2, ADR-005).
//! Generated exclusively by the mirror gate; never self-generated by clients.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CapabilityManifest {
    pub schema_version: u32,
    /// The exact raw digest this capability manifest was generated for.
    pub bound_raw_digest: String,
    pub codex_version: String,
    pub generated_at: String,
    pub skin_compat: SkinCompatibility,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SkinCompatibility {
    /// Overall compatibility verdict
    pub compatible: bool,
    /// Specific checks that were performed
    pub checks: Vec<CompatCheck>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompatCheck {
    pub name: String,
    pub passed: bool,
    pub detail: Option<String>,
}

impl CapabilityManifest {
    /// Returns true iff this capability manifest was generated for the given raw digest.
    pub fn matches_digest(&self, raw_digest: &str) -> bool {
        self.bound_raw_digest == raw_digest
    }
}
