// @generated by scripts/generate-branding.ps1 — DO NOT EDIT BY HAND

export const DISPLAY_SILENT_NAME = 'Chimera++';
export const DISPLAY_MANAGER_NAME = 'Chimera++ 管理工具';
export const PUBLISHER = 'ChimeraHub';
export const REPOSITORY = 'Duojiyi/chimera-codex';
export const LATEST_JSON_URL = 'https://github.com/Duojiyi/chimera-codex/releases/latest/download/latest.json';
export const DEFAULT_RELAY_BASE_URL = 'https://api.chimerahub.org/v1';
export const DEFAULT_RELAY_MODEL = 'gpt-5.5';
export const ARTIFACT_PREFIX = 'ChimeraPlusPlus';
export const MACOS_BUILD_NUMBER = 4;
export const WEBSITE_URL = 'https://api.chimerahub.org/';
export const API_KEY_URL = 'https://api.chimerahub.org/';
