#Requires -Version 5.1
<#
.SYNOPSIS
  Generate Rust/TS branding files from brand/product.toml.

.PARAMETER Check
  Regenerate into a temp directory and byte-compare against the working tree.
  Does not modify tracked generated files.
#>
[CmdletBinding()]
param(
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-RepoRoot {
    $scriptDir = Split-Path -Parent $PSCommandPath
    return (Resolve-Path (Join-Path $scriptDir '..')).Path
}

function Read-FlatToml {
    param([Parameter(Mandatory)][string]$Path)

    $map = [ordered]@{}
    foreach ($raw in Get-Content -LiteralPath $Path -Encoding UTF8) {
        $line = $raw.Trim()
        if ($line -eq '' -or $line.StartsWith('#')) { continue }
        if ($line -match '^\s*\[') {
            throw "Nested TOML tables are not supported in brand/product.toml: $line"
        }
        if ($line -notmatch '^\s*([A-Za-z0-9_]+)\s*=\s*(.+)\s*$') {
            throw "Unable to parse TOML line: $raw"
        }
        $key = $Matches[1]
        $value = $Matches[2].Trim()
        if ($value -match '^"(.*)"$') {
            $map[$key] = $Matches[1]
        }
        elseif ($value -match '^(true|false)$') {
            $map[$key] = [bool]::Parse($value)
        }
        elseif ($value -match '^-?\d+$') {
            $map[$key] = [int]$value
        }
        else {
            throw "Unsupported TOML value for key '$key': $value"
        }
    }
    return $map
}

function Require-Keys {
    param(
        [Parameter(Mandatory)]$Map,
        [Parameter(Mandatory)][string[]]$Keys
    )
    foreach ($key in $Keys) {
        if (-not $Map.Contains($key)) {
            throw "brand/product.toml missing required key: $key"
        }
    }
}

function Assert-NoPlaceholders {
    param([Parameter(Mandatory)]$Map)

    $forbidden = @('TBD', 'example', 'chimera-org', 'BigPizzaV3/CodexPlusPlus')
    $scanKeys = @(
        'display_silent_name', 'display_manager_name', 'publisher', 'repository',
        'latest_json_url', 'default_relay_base_url', 'default_relay_model',
        'artifact_prefix', 'website_url', 'api_key_url'
    )
    foreach ($key in $scanKeys) {
        $text = [string]$Map[$key]
        foreach ($token in $forbidden) {
            if ($text -like "*$token*") {
                throw "Placeholder or forbidden value in ${key}: contains '$token'"
            }
        }
    }

    if ($Map['repository'] -ne 'Duojiyi/chimera-codex') {
        throw "repository must be Duojiyi/chimera-codex, got: $($Map['repository'])"
    }

    $expectedLatest = "https://github.com/$($Map['repository'])/releases/latest/download/latest.json"
    if ($Map['latest_json_url'] -ne $expectedLatest) {
        throw "latest_json_url must be $expectedLatest"
    }

    if ($Map['ads_enabled'] -ne $false) {
        throw 'ads_enabled must be false'
    }

    if ([int]$Map['macos_build_number'] -lt 1) {
        throw 'macos_build_number must be a positive integer'
    }

    if (-not ([string]$Map['default_relay_base_url']).EndsWith('/v1')) {
        throw 'default_relay_base_url must end with /v1'
    }
}

function Escape-RustString([string]$Value) {
    return ($Value -replace '\\', '\\' -replace '"', '\"')
}

function Escape-TsString([string]$Value) {
    return ($Value -replace '\\', '\\' -replace "'", "\'")
}

function New-RustBranding {
    param([Parameter(Mandatory)]$Map)

    $ads = if ($Map['ads_enabled']) { 'true' } else { 'false' }
    $lines = @(
        '// @generated by scripts/generate-branding.ps1 — DO NOT EDIT BY HAND'
        '#![allow(dead_code)]'
        ''
        "pub const DISPLAY_SILENT_NAME: &str = `"$(Escape-RustString $Map['display_silent_name'])`";"
        "pub const DISPLAY_MANAGER_NAME: &str = `"$(Escape-RustString $Map['display_manager_name'])`";"
        "pub const PUBLISHER: &str = `"$(Escape-RustString $Map['publisher'])`";"
        "pub const REPOSITORY: &str = `"$(Escape-RustString $Map['repository'])`";"
        "pub const LATEST_JSON_URL: &str = `"$(Escape-RustString $Map['latest_json_url'])`";"
        "pub const ADS_ENABLED: bool = $ads;"
        "pub const DEFAULT_RELAY_BASE_URL: &str = `"$(Escape-RustString $Map['default_relay_base_url'])`";"
        "pub const DEFAULT_RELAY_MODEL: &str = `"$(Escape-RustString $Map['default_relay_model'])`";"
        "pub const ARTIFACT_PREFIX: &str = `"$(Escape-RustString $Map['artifact_prefix'])`";"
        "pub const MACOS_BUILD_NUMBER: u32 = $([int]$Map['macos_build_number']);"
        "pub const WEBSITE_URL: &str = `"$(Escape-RustString $Map['website_url'])`";"
        "pub const API_KEY_URL: &str = `"$(Escape-RustString $Map['api_key_url'])`";"
        ''
    )
    return ($lines -join "`n")
}

function New-TsBranding {
    param([Parameter(Mandatory)]$Map)

    $ads = if ($Map['ads_enabled']) { 'true' } else { 'false' }
    $lines = @(
        '// @generated by scripts/generate-branding.ps1 — DO NOT EDIT BY HAND'
        ''
        "export const DISPLAY_SILENT_NAME = '$(Escape-TsString $Map['display_silent_name'])';"
        "export const DISPLAY_MANAGER_NAME = '$(Escape-TsString $Map['display_manager_name'])';"
        "export const PUBLISHER = '$(Escape-TsString $Map['publisher'])';"
        "export const REPOSITORY = '$(Escape-TsString $Map['repository'])';"
        "export const LATEST_JSON_URL = '$(Escape-TsString $Map['latest_json_url'])';"
        "export const ADS_ENABLED = $ads;"
        "export const DEFAULT_RELAY_BASE_URL = '$(Escape-TsString $Map['default_relay_base_url'])';"
        "export const DEFAULT_RELAY_MODEL = '$(Escape-TsString $Map['default_relay_model'])';"
        "export const ARTIFACT_PREFIX = '$(Escape-TsString $Map['artifact_prefix'])';"
        "export const MACOS_BUILD_NUMBER = $([int]$Map['macos_build_number']);"
        "export const WEBSITE_URL = '$(Escape-TsString $Map['website_url'])';"
        "export const API_KEY_URL = '$(Escape-TsString $Map['api_key_url'])';"
        ''
    )
    return ($lines -join "`n")
}

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Content
    )
    $dir = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

function Compare-FilesExact {
    param(
        [Parameter(Mandatory)][string]$ExpectedPath,
        [Parameter(Mandatory)][string]$ActualPath
    )
    if (-not (Test-Path -LiteralPath $ActualPath)) {
        throw "Missing generated file in working tree: $ActualPath"
    }
    $expected = [System.IO.File]::ReadAllBytes($ExpectedPath)
    $actual = [System.IO.File]::ReadAllBytes($ActualPath)
    if ($expected.Length -ne $actual.Length) {
        throw "Generated drift (length): $ActualPath"
    }
    for ($i = 0; $i -lt $expected.Length; $i++) {
        if ($expected[$i] -ne $actual[$i]) {
            throw "Generated drift (byte $i): $ActualPath"
        }
    }
}

$root = Get-RepoRoot
$tomlPath = Join-Path $root 'brand\product.toml'
if (-not (Test-Path -LiteralPath $tomlPath)) {
    throw "Missing $tomlPath"
}

$map = Read-FlatToml -Path $tomlPath
Require-Keys -Map $map -Keys @(
    'display_silent_name', 'display_manager_name', 'publisher', 'repository',
    'latest_json_url', 'ads_enabled', 'default_relay_base_url', 'default_relay_model',
    'artifact_prefix', 'macos_build_number', 'website_url', 'api_key_url'
)
Assert-NoPlaceholders -Map $map

$rustContent = New-RustBranding -Map $map
$tsContent = New-TsBranding -Map $map

$rustRel = 'crates\codex-plus-core\src\branding.rs'
$tsRel = 'apps\codex-plus-manager\src\branding.generated.ts'
$rustPath = Join-Path $root $rustRel
$tsPath = Join-Path $root $tsRel

if ($Check) {
    $tempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("chimera-branding-check-" + [guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $tempRoot -Force | Out-Null
    try {
        $tempRust = Join-Path $tempRoot 'branding.rs'
        $tempTs = Join-Path $tempRoot 'branding.generated.ts'
        Write-Utf8NoBom -Path $tempRust -Content $rustContent
        Write-Utf8NoBom -Path $tempTs -Content $tsContent
        Compare-FilesExact -ExpectedPath $tempRust -ActualPath $rustPath
        Compare-FilesExact -ExpectedPath $tempTs -ActualPath $tsPath
        Write-Host 'generate-branding -Check: PASS'
    }
    finally {
        Remove-Item -LiteralPath $tempRoot -Recurse -Force -ErrorAction SilentlyContinue
    }
}
else {
    Write-Utf8NoBom -Path $rustPath -Content $rustContent
    Write-Utf8NoBom -Path $tsPath -Content $tsContent
    Write-Host "Wrote $rustRel"
    Write-Host "Wrote $tsRel"
}
